packages:
  - 'internal-examples/*'

catalog:
  "@types/node": "^22"
  "@skyway-sdk/room": "2.1.0" # type errors about SkyWayContext raised in v2.3.0
  "@eslint/js": "^9.39.1"
  "@skyway-sdk/token": "^2.1.0"
  "eslint": "^9.39.1"
  "eslint-plugin-react-hooks": "^7.0.1"
  "eslint-plugin-react-refresh": "^0.4.24"
  "globals": "^16.5.0"
  "typescript": "~5.9.3"
  "typescript-eslint": "^8.46.4"
  "vite": "^7.2.4"
